/// NO-NETWORK-TYPES ///
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

/// AUTHORIZATION TYPES ///
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const FETCH_FEIDE_USER_SUCCESS = 'FETCH_FEIDE_USER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const PRIVACY_CONSENT_LOADING = 'PRIVACY_CONSENT_LOADING';
export const PRIVACY_CONSENT_RETURN = 'PRIVACY_CONSENT_RETURN';

/// ACCOUNT ACTIONS ///
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
export const SUBJECT_LIST = 'SUBJECT_LIST';
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT';
export const GET_USER = 'GET_USER';
export const ROLE_ERROR = 'ROLE_ERROR';
export const SELECT_SUBJECTS_WITH_TEAMS = 'SELECT_SUBJECTS_WITH_TEAMS';

// STUDENT ACTIONS 
export const FETCH_TEAM_LIST = 'FETCH_TEAM_LIST';
export const FETCH_LOADING = 'FETCH_LOADING';
export const STUDENT_ACTION_LOADING = 'ACTION_LOADING';
export const SELECT_TEAM_OK = 'SELECT_TEAM_OK';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const FETCH_TEAM_STATUS = 'FETCH_TEAM_STATUS';
export const REGISTER_SCORE = 'REGISTER_SCORE';
export const FETCH_TEAM = 'FETCH_TEAM';
export const CONTACT_INFO = 'CONTACT_INFO';
export const HISTORY_SCORES = 'HISTORY_SCORES';

// STAFF ACTIONS ///
export const FETCH_STAFF_SUBJECTS = 'FETCH_STAFF_SUBJECTS';
export const STAFF_FETCH_LOADING = 'STAFF_FETCH_LOADING';
export const STAFF_OVERVIEW = 'STAFF_OVERVIEW';
export const STAFF_FETCH_TEAMS = 'STAFF_FETCH_TEAMS';
export const GET_TEAM_INFO = 'GET_TEAM_INFO';
export const MODAL_LOADER = 'MODAL_LOADER';
export const SET_STAFF_FIELD = 'SET_STAFF_FIELD';
export const GET_AUTH = 'GET_AUTH';

// ADMIN ACTIONS // 
export const ADMIN_ACTION_LOADING = 'ADMIN_ACTION_LOADING';
export const TEAM_UPLOAD_SUCCESS = 'TEAM_UPLOAD_SUCCESS';