/// NO-NETWORK-TYPES ///
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

/// AUTHORIZATION TYPES ///
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const FETCH_FEIDE_USER_SUCCESS = 'FETCH_FEIDE_USER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

/// ACCOUNT ACTIONS ///
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const EDIT_PROFILE_LOADING = 'EDIT_PROFILE_LOADING';
export const SUBJECT_LIST = 'SUBJECT_LIST';
