/// NO-NETWORK-TYPES ///
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

/// AUTHORIZATION TYPES ///
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const FETCH_FEIDE_USER_SUCCESS = 'FETCH_FEIDE_USER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

/// ACCOUNT ACTIONS ///
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
export const SUBJECT_LIST = 'SUBJECT_LIST';
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT';

// STUDENT ACTIONS 
export const FETCH_TEAM_LIST = 'FETCH_TEAM_LIST';
export const FETCH_LOADING = 'FETCH_LOADING';
export const STUDENT_ACTION_LOADING = 'ACTION_LOADING';
export const SELECT_TEAM_OK = 'SELECT_TEAM_OK';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const FETCH_TEAM_STATUS = 'FETCH_TEAM_STATUS';
export const REGISTER_SCORE = 'REGISTER_SCORE';